import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NextTopLoader from "nextjs-toploader";
import Footer from "@/com/Footer";
import Miniheader from "@/com/Miniheader";

export const metadata = {
  title: "portfolio",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NextTopLoader
            color="#5b21b6"
            initialPosition={0.18}
            crawlSpeed={500}
            height={3}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={200}
          />
          <Miniheader />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
